### ISSUE TITLE
Убрать ошибку валидации при изменении slug проекта, если slug не менялся

### ISSUE THREAD

**Issue by EugZol** [qkspace/qkspace#103]
Условия: есть проект

**Шаги**:

* Зайти на страницу редактирования проекта (projects/:id/edit)
* Изменить slug, дождаться появления сообщения валидации под текстовым полем
* Вернуть slug на прежний — какой у проекта и был изначально

**Результат**:

Под текстовым полем появляется ошибка валидации, мол slug уже занят.

**Ожидалось**:

Ошибки валидации нет.

![2019-02-18_21-09-33](https://user-images.githubusercontent.com/835/52969459-81bf1880-33c1-11e9-8714-2fa9306fc84e.png)

**Comment by tarrinros** [comment]
Могу предложить 3 способа решения этой проблемы:

1. Очищать slug проекта в БД в момент, когда пользователь кликает по полю редактирования slug
2. Очищать slug проекта в БД в момент, когда пользователь удаляет хотя бы один символ из поля slug в формe редактирования
3.  Создать сущность Slug и связать её с Project has_one / belongs_to. Соответственно валидировать уникальность, если ID редактируемого проекта не совпадает с slug.project_id

**Comment by installero** [comment]
> Какой-нибудь из них подойдет?

Денис уже кинул PR, можете посмотреть, как он сделал.
