### ISSUE TITLE
Добавить logo в README и README.ru

### ISSUE THREAD

**Issue by EugZol** [qkspace/qkspace#107]

**Comment by installero** [comment]
[qk-space.png.zip](https://github.com/qkspace/qkspace/files/2905971/qk-space.png.zip)

**Comment by sas2job** [comment]
Куда положить картинку (github или свой хостинг)?
Куда будет вести картинка?
Будет ли отслеживаться клик?
Дизайн есть (как нужно расположить картинку, ее размеры(сейчас 1500 * 1200))?

**Comment by installero** [comment]
> Можем на 6-8 мая, если Ася поправится. 

В этот же репозиторий в `/public/images/logo.png`, например.

>  Куда будет вести картинка?

Никуда.

>  Будет ли отслеживаться клик?

Нет.

>  Дизайн есть (как нужно расположить картинку, ее размеры(сейчас 1500 * 1200))?

Размер нужно какой-то разумный подобрать, я думаю, 300x240 будет норм, но лучше посмотреть и прислать скрин.

Про расположение не понял вопроса, а какое расположение позволяет сделать MarkDown кроме обычного (слева вровень с линией текста)?

**Comment by sas2job** [comment]
PR принят, ишью закройте?
