### ISSUE TITLE
Вывод 500 ошибки при изменении личных данных аккаунта

### ISSUE THREAD

**Issue by kuzminvn2010** [qkspace/qkspace#113]
#### Шаги: 
- регистрируемся на http://qkspace.com/sign_in
- заходим по адресу http://qkspace.com/users/edit 
- нажимаем на баттон Update 
#### Результат:
Получам  вывод 500 ошибки
#### Ожидалось:
 Ошибки быть не должно

**Но несмотря на это**, если перейти на предыдущую страницу  (снова на  http://qkspace.com/users/edit) и затем на http://qkspace.com/projects  видно что email  успешно изменился

**Comment by installero** [comment]
![Screenshot from 2019-04-22 10-27-28](https://user-images.githubusercontent.com/42387/56489100-420fcc80-64e9-11e9-801c-c0e810b24eec.png)

Пофиксил:

https://github.com/qkspace/qkspace/pull/114
