### ISSUE TITLE
Волшебная ссылка при логине попадает в спам на gmail

### ISSUE THREAD

**Issue by installero** [qkspace/qkspace#119]
subj

**Comment by Arlantir** [comment]
Я так понимаю, это задача более не актуальна.

Проверил:

Зарегистрировался.
Вышел и отправил **Волшебную ссылку**
Письмо упало в **Входящие**

**Comment by installero** [comment]
Раз на раз не приходится. Надо отправить ссылку на какой-нить ящик типа [такого](https://www.mail-tester.com/) и посмотреть, что будет.

**Comment by Arlantir** [comment]
> Надо отправить ссылку на какой-нить ящик типа такого и посмотреть, что скажут.

Письма на данные сервис не доходят, залез на **mailtrap**,  спам репорт выдаёт значение **0.7**,  **0.6** - вытекает от сюда `HTML-only message, but there is no HTML tag`, но я не думаю, что в этом может быть проблем, а вот то что проект находится в **черном списке**, вполне допускаю.

**Blacklists Report**
[Listed in BARRACUDA](https://barracudacentral.org/rbl)

Но там как сказано, [нужно предоставить реальные данные](https://barracudacentral.org/rbl/removal-request)

**Comment by installero** [comment]
> Письма на данные сервис не доходят, залез на mailtrap, спам репорт выдаёт значение 0.7, 0.6 - вытекает от сюда HTML-only message, but there is no HTML tag, но я не думаю, что в этом может быть проблема, а вот то что проект находится в черном списке, вполне допускаю.

С продакшна всё доходит:

https://www.mail-tester.com/test-h29okchx3

Тестировать с development смысла нет, т.к. важно проверить отправку именно с сервера проекта.

**Comment by Arlantir** [comment]
Я тогда не очень понимаю, что не так.

Как я понял, иногда линк попадает в спам на проде, судя по сервису для проверки, мы имеем оценку -1,5, что допустимо и спамом считается всё что ниже -5.

**Comment by installero** [comment]
Ну однозначно есть, что улучшить :)

**Comment by Arlantir** [comment]
Добавил текстовые письма для **ru/en**, для веба завернул в ген `html`.

Индекс спама по идее должен снизиться.

**Comment by Arlantir** [comment]
Ну я ориентировался на два сервиса:

[1](https://www.mail-tester.com/ ) 
[2](https://mailtrap.io/)

1.  Сообщает: **HTML-only message, but there is no HTML tag
Ваше сообщение должно содержать тег <html>**

2. Сообщает: **HTML-only message, but there is no HTML tag**

Так же у майлтрапа в закладке **HTML Source**  из html, только тег `a`

![image](https://user-images.githubusercontent.com/11597534/81200755-14e76c80-8fcd-11ea-8e00-f4df89c7d3fc.png)

**Comment by Arlantir** [comment]
Чего то я совсем не пойму, как работают эти анализаторы, сейчас без шаблона всё хорошо, но теперь ругается на другое, что текстовое письмо не соответствует html.

[как то так](https://www.mail-tester.com/test-lv9xp5tcc)

**Comment by installero** [comment]
![Screenshot from 2020-05-08 10-51-47](https://user-images.githubusercontent.com/42387/81384206-fc389d00-9119-11ea-8a3d-49c2cb806881.png)

Ну вот это полюбому надо поправить, как ни крути, так что ваш PR вполне уместен.

**Comment by Arlantir** [comment]
> Ну вот это полюбому надо поправить, как ни крути, так что ваш PR вполне уместен.

Мне кажется это с вашего теста, а я приложил свою версию, и там сейчас по другому, хотя я вообще удалил `html` теги.

До этого был результат как у вас.

**Comment by installero** [comment]
Откуда вы удалили HTML-теги? o_O

**Comment by Arlantir** [comment]
То что в ПР добавлял, оборачивал текст письма в `html` теги, сейчас их удалил и попробовал снова проверить, вот выдаёт то что выше по ссылке, то есть больше не ругается, что в письме нет `html` тега.

**Comment by installero** [comment]
Ещё раз:

> Тестировать с development смысла нет, т.к. важно проверить отправку именно с сервера проекта.

Вы шлете со своего GMail-овского SMTP-сервера, он может оборачивать принудительно тело в html перед шифрованием.

Зато ругается на такое:

![Screenshot from 2020-05-08 11-14-03](https://user-images.githubusercontent.com/42387/81386050-0f993780-911d-11ea-8b4a-762db326304a.png)

Ну и нет смысла слать HTML без `<html>`-тега.

**Comment by Arlantir** [comment]
Так, вроде поправил + поправил опечатки в `views/layouts/application`

**Comment by installero** [comment]
Надеюсь, #141 поможет. Пока закрою.
