### ISSUE TITLE
Автогенерация og:image для статей

### ISSUE THREAD

**Issue by installero** [qkspace/qkspace#137]
Сейчас, если кинуть в телегу ссылку на любую статью, будет так:

![Screenshot from 2020-04-21 12-37-13](https://user-images.githubusercontent.com/42387/79850595-d8145680-83cc-11ea-8349-17127f79f383.png)

Надо автоматически генерить из текста, чтобы было как-то так:

<img width="602" alt="tweet" src="https://user-images.githubusercontent.com/42387/79850711-f8dcac00-83cc-11ea-80ee-dee11d4ad28e.png">

С помощью вот этого сервиса https://github.com/zeit/og-image. Полюбому должны быть обертки на руби.

**Comment by prisioner** [comment]
на руби есть вот такое - https://github.com/csquared/IMGKit - генерация картинки из html-кода - сделать небольшой partial и генерировать из него картинку

**Comment by installero** [comment]
Круто!

Тут уже трудятся вовсю: #138
