### ISSUE TITLE
Ограничить большие картинки по ширине

### ISSUE THREAD

**Issue by installero** [qkspace/qkspace#157]
Сейчас при вставке большой картинки получается так:

![Screenshot from 2020-07-11 11-23-33](https://user-images.githubusercontent.com/42387/87220000-fd2fba00-c368-11ea-96f4-4eaddcbba8c8.png)

Возможное решение — дописать картинкам на страницах стиль `mad-width: 100%`.

**Comment by sas2job** [comment]
Дописать картинкам на страницах стиль в самом редакторе?
