### ISSUE TITLE
Домены второго уровня

### ISSUE THREAD

**Issue by EugZol** [qkspace/qkspace#33]
Подготовительные мероприятия:

* Сделать так, чтобы на `ruby.qkspace.com` нельзя было ничего редактировать
* Добавить страницу редактирования (`qkspace.com/projects/ruby`)

Потом простая часть: прикрутить возможность указывать свои домены второго уровня для проекта.

**Comment by EugZol** [comment]
- [ ] Придумать, как проверять домены (что они принадлежат юзеру)
- [ ] Добавить поле модели
- [ ] Добавить воркера, который проверяет принадлежность
- [ ] Изменить 18-ю строчку `PublicController`

**Comment by prisioner** [comment]
нужно ли нам проверять принадлежность домена? или же достаточно того, что юзер обладает полномочиями направить домен на наш сервер? (вероятно через CNAME-запись на поддомен со своим проектом)

**Comment by EugZol** [comment]
Хороший вопрос. Я думаю нужно. Например, что делать, если ДВА пользователя указали один и тот же домен?

**Comment by prisioner** [comment]
мои размышления как делал бы я

использовать что-то типа 
http://ruby-doc.org/stdlib-2.5.1/libdoc/resolv/rdoc/Resolv/DNS.html

Использовать 2 поля, одно для хранения поля, другое как признак активности.
Поставить констрэйнт уникальности на связку имя домена + позиция "активный" (включая констрэйнт на уровне БД)

флоу:
1. Пользователь указывает домен кандидат
2. Запускается наш воркер, который проверяет наличие валидной CNAME записи
3. Воркер работает ограниченное количество попыток (в течении суток-полутора, сколько надо на обновление DNS записей максимум?)
4. Воркер видит валидную запись - делает update!
5. Если ловит ActiveRecord::RecordNotUnique - дизапрувит домен в другом проекте и повторно апрувит в нужном. Таким образом старый домен "сам" отвалится, когда новый владелец захочет его использовать для другого своего проекта (условно)
6. Если по истечении заданного количества попыток валидной записи нет - уведомляем юзера

**Comment by prisioner** [comment]
Вероятно, стоит предусмотреть так же возможность привязки проекта на qkspace к домену третьего уровня (поддомен на своем сайте)?

**Comment by EugZol** [comment]
Т.е. указав чужой домен в своём проекте я могу его открутить от старого проекта?

**Comment by EugZol** [comment]
> Вероятно, стоит предусмотреть так же возможность привязки проекта на qkspace к домену третьего уровня (поддомен на своем сайте)?

Конечно, custom domain может быть любого уровня.

**Comment by prisioner** [comment]
> Т.е. указав чужой домен в своём проекте я могу его открутить от старого проекта?

Нет, т.к. он не пройдёт этап проверки CNAME-записи - запись будет вести не на тот адрес, который нужен

**Comment by EugZol** [comment]
А на какой нужен?

**Comment by prisioner** [comment]
Вообще получается это будет работать так:

Браузер -> DNS: mydomain.com - какой ip-шник?
DNS -> Браузер: такой же как у myproject.qkspace.com
Браузер -> DNS: ок, какой ip-шник у myproject.qkspace.com ?
DNS -> Браузер: 192.81.221.67
Браузер -> 192.81.221.67: Привет, mydomain.com, я к тебе

Сервер проверяет, для какого проекта зааппрувлен mydomain.com и показывает его. Даже если slug этого проекта уже изменился - он будет выводиться, т.к. у нас один сервер, где всё лежит.

Если кто-то захватит старый слаг и укажет там чужой домен - он перепривяжется, т.к. там указана старая CNAME-запись, которую наша проверка сочтёт актуальной, но я не вижу в этом большой беды, т.к. это зона ответственности владельца домена следить за актуальностью CNAME-записи и соответствие slug. Владелец домена сможет изменить запись и проинициировать проверку в нашем интерфейсе заново проапдейтив поле с доменом и обратно всё перепривязать. Кроме того, @installero предлагал запретить изменение slug для проектов старше месяца.

**Comment by EugZol** [comment]
Ну, можно CNAME ставить не на slug, а, например, на ID проекта: `123.qkspace.com`.

**Comment by installero** [comment]
> А если slug проекта поменяется? А если старый slug кто-нибудь захватит?

Я всерьёз думаю, что менять `slug` проекта — плохая затея. Если проект хоть скольнибудь значим, то никто его адрес менять не будет. Можно лочить смену слага, скажем, через месяц после создания проекта.

> Ну, можно CNAME ставить не на slug, а, например, на ID проекта: 123.qkspace.com.

Тоже выход. Как бы то ни было, мы напишем короткую инструкцию.

Классический способ проверить привязку — искусственные CNAME-записи:

https://yandex.ru/support/pdd/setting/confirm.html

> Создайте новую CNAME-запись со следующими значениями полей (в разных панелях управления названия полей могут отличаться):
>
> Имя — поддомен вашего домена, имя которого совпадает со строкой, указанной на странице подтверждения.
>
> Например, на странице подтверждения указана строка «yamail-123456abcdef», и вы хотите подтвердить домен «yourdomain.tld». Имя CNAME-записи следует задать так: «yamail-123456abcdef.yourdomain.tld.» (с точкой в конце).
>
> В некоторых панелях управления не нужно добавлять точку в конце имени записи или требуется ввести только строку для подтверждения, например, «yamail-123456abcdef».
>
> Значение — «mail.yandex.net.» (с точкой в конце).
>
> Точка в конце имени сервера обязательна, кроме тех случаев, когда ваша панель управления добавляет эту точку по умолчанию.

**Comment by EugZol** [comment]
> Я всерьёз думаю, что менять slug проекта — плохая затея. Если проект хоть сколь-нибудь значим, то никто его адрес менять не будет. Можно лочить смену слага, скажем, через месяц после создания проекта.

Тогда месяц можно будет провернуть эту схему с уводом домена? :)

> Классический способ проверить привязку — искусственные CNAME-записи

Да, это совсем надёжно. Вот вопрос, а чем это надёжней, чем ставить CNAME, указывающий с сервера юзера на наш сервер — не `<code>.yourodmain.tld`, а `<code>.qkspace.com`. Тогда CNAME одновременно и для валидации, и для переадресации. Яндексу-то не надо, чтобы юзерский домен вёл на Яндекс.

**Comment by installero** [comment]
> Тогда месяц можно будет провернуть эту схему с уводом домена? :)

Можно лочить смену поддомена, если привязал домен (что в общем-то логично).

**Comment by EugZol** [comment]
Решение для поддержки доменов второго уровня:

* Ставить CNAME на `www` -> `<project_id>.qkspace.com`
* Ставить A на IP qkspace.com
* Делать редирект с `x.y` на `www.x.y` на уровне `nginx`

Первые два пункта надо просто внести в справку.

**Comment by EugZol** [comment]
Надо дописать в справку указанный выше способ работы с доменами второго уровня.

**Comment by EugZol** [comment]
Вроде здесь больше ничего не требуется?
