### ISSUE TITLE
Когда стоишь в Title и жмешь на клаве Tab, фокус переходит не пойми куда, а не в Content

### ISSUE THREAD

**Issue by inem** [qkspace/qkspace#59]

**Comment by installero** [comment]
Подтверждаю, ToastUI так не умеет.

**Comment by Combos93** [comment]
Коллеги, а что есть Title, и что такое конкретно Content ?

**Comment by installero** [comment]
![Screenshot from 2019-08-04 12-31-04](https://user-images.githubusercontent.com/42387/62421995-d1fe0e80-b6b3-11e9-8f55-5c094743fa98.png)

**Comment by Combos93** [comment]
Есть идея: задействовать Action Text вместо Toast UI? И возможно тогда на него курсор будет переходить...

Сейчас уже "можно". Rails 6.0.0 официально появились.

Хотя в доке Тоаста я нашел один метод-функцию, но хз как его применить

Но, возникает вопрос: а сохраняет ли ActionText в markdown или нет...

I played around with Trix when it first came out and like it. The new editor will also be markdown, but if we offer a WYSIWYG in the future, we'll definitely look at it as an option.

Это то, что нашёл по поводу Маркдауна

**Comment by installero** [comment]
> 
> 
> **Есть идея:** задействовать Action Text вместо Toast UI? И возможно тогда на него курсор будет переходить...
> 
> Сейчас уже "можно". Rails 6.0.0 официально появились.
> 
> Хотя в доке Тоаста я нашел один метод-функцию, но хз как его применить
> 
> Но, возникает вопрос: а сохраняет ли ActionText в markdown или нет...
> 
> > I played around with Trix when it first came out and like it. The new editor will also be markdown, but if we offer a WYSIWYG in the future, we'll definitely look at it as an option.
> 
> Это то, что нашёл по поводу Маркдауна

**Comment by installero** [comment]
#126
