### ISSUE TITLE
Баг с транслитом при написании русского заголовка страницы в en локали

### ISSUE THREAD

**Issue by installero** [qkspace/qkspace#77]
Если сохранить стоаницу в en локали, будет http://ruby.qkspace.com/windows, если в ru, будет http://ruby.qkspace.com/windows-problema-s-kodirovkoy-russkimi-bukvami

**Comment by EugZol** [comment]
```
<%= f.input :slug, hint: '', input_html: { data: { locale: I18n.locale } } %>
```

Выпилить вот этот костыль.

**Comment by OlgaCoskun** [comment]
я выпилила эту строку полностью) но проблема не решилась... разбираююсь дальше

**Comment by EugZol** [comment]
Этот костыль как-то призван был решить исходную проблему, как я понял.

А настоящим решением будет просто использовать какой-нибудь сторонний gem транслитерации, который в независимости от языка локали будет все символы преобразовывать. Сейчас работает вот так:

```
$ rails c
Loading development environment (Rails 5.2.1)
2.4.1 :001 > I18n.locale = :en
 => :en
2.4.1 :002 > I18n.transliterate('Тест')
 => "????"
2.4.1 :003 > I18n.locale = :ru
 => :ru
2.4.1 :004 > I18n.transliterate('Тест')
 => "Test"
```

**Comment by prisioner** [comment]
> я выпилила эту строку полностью) но проблема не решилась... разбираююсь дальше

радикально, но эта строка никак не связана с проблемой, это отдельный костыль, который почему-то приплюсовали сюда :) И костылём там является только вот эта часть `, input_html: { data: { locale: I18n.locale } }` (про которую так же надо вспомнить будет в JS)

Проблема заключается в том, что I18n.transliterate ведёт себя по-разному при разных локалях.

**Comment by EugZol** [comment]
> радикально, но эта строка никак не связана с проблемой, это отдельный костыль, который почему-то приплюсовали сюда :)

а куда надо было? :)

**Comment by prisioner** [comment]
> Этот костыль как-то призван был решить исходную проблему, как я понял.

Нет, этот костыль был во имя того, что я думал, что с JS-запросом сессия не уйдёт и всегда будет default-локаль возвращаться) В отдельный issue тогда уж уместнее :)

**Comment by OlgaCoskun** [comment]
надо лезть в JS ?
