### ISSUE TITLE
Добавить anchors для заголовков

### ISSUE THREAD

**Issue by EugZol** [qkspace/qkspace#93]
Сделать так, чтобы при наведении на заголовок (внутри текста страницы) можно было скопировать anchor-ссылку на этот заголовок.

**Comment by installero** [comment]
Задача состоит из двух частей:

[ ] При сохранении страницы добавить в обработчик содержания правило для обработки заголовков (менять `### ...` не на `<h3>...</h3>`, а на `<h3 id="...">...</h3>`.
[ ] Добавить (с пом. JS) к страницам обработчик событий наведения на заголовок: показывать иконку-ссылку [fa-link](https://fontawesome.com/v4.7.0/icon/link).

**Comment by Gargantua88** [comment]
Переписать метод используемого для парсинга гема, отвечающий за сохранение header`ов - норм решение?

И на приватной странице проекта линки на заголовки так же можно копировать? В этом случае они будут вести уже на публичный адрес этой страницы, с поддоменом? типа я копирую anchor-ссылку, находясь на http://qkspace.com/projects/45/pages/133 а она копируется как ссылка на, скажем http://beautifulrussia.qkspace.com/vot-ona-kakaya#anchor1 ?

**Comment by installero** [comment]
> Переписать метод используемого для парсинга гема, отвечающий за сохранение header`ов - норм решение?

Не вижу других решений.

> И на приватной странице проекта линки на заголовки так же можно копировать?

Они там не нужны, но да, они там будут такие же, как и на публичной (мы ж html страницы сохраняем).

> И сами якоря можно делать как anchor1, anchor2, ... или туда надо записывать значение header? Просто если значение, то они могут быть не уникальны

```
### Важный заголовок
```

Должен превратиться в

```
<h3 it="vazhniy-zagolovok">Важный заголовок</h3>
```

Транслит — по аналогии с заголовком страницы (см. модель `page.rb`).

**Comment by installero** [comment]
#97
