### ISSUE TITLE
Ссылки на хедеры (headers): правки внешнего вида

### ISSUE THREAD

**Issue by EugZol** [qkspace/qkspace#99]
В продолжение #97 

1. Уменьшить размер значка "цепочки" рядом со ссылкой. М.б. стоит сделать его размер универсальным, в независимости от шрифта (уровня заголовка).
2. Анимацию появления/исчезания убрать, либо ускорить в 5-10 раз.
3. При клике копировать в буфер обмена.

**Comment by Gargantua88** [comment]
3. А функцию перехода полностью убираем, только копирование?

**Comment by EugZol** [comment]
Давай пока вообще без копирования – оставить переход как сейчас. Надо посмотреть, как получится при изменении только внешнего вида.

**Comment by installero** [comment]
Поправил дизайн, немного отрефакторил CSS

**Comment by EugZol** [comment]
Уточнение задания. Речь идёт о значке `#` рядом с заголовками. Например: http://ruby.qkspace.com/ruby-dvoynye-kavychki-vs-odinarnye#dvoynye-kavychki

1. Анимацию появления/исчезания убрать, либо ускорить в 5-10 раз.
2. При клике копировать в буфер обмена.

**Comment by EugZol** [comment]
#161
